PIPELINE_VERSION = "1.0"
AGGREGATION_VERSION = "max_confidence_v1"
REFERENCE_HCPCS_VERSION = "2026.01"

CONFIDENCE_THRESHOLD = 0.65

MODEL_NAME = "mock-gpt-4"
MODEL_VERSION = "1.0"
PROMPT_TEMPLATE_VERSION = "1.0"